// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"neema.co.za/rest/api/handlers"
	"neema.co.za/rest/app"
	"neema.co.za/rest/database"
	"neema.co.za/rest/repository"
	"neema.co.za/rest/service"
)

// Injectors from wire_user.go:

func injectUserModule() *handlers.UserHandler {
	databaseDatabase := database.GetDatabase()
	userRepository := repository.NewUserRepository(databaseDatabase)
	userService := service.NewUserService(userRepository)
	routerCreator := app.NewRouter()
	userHandler := handlers.NewUserHandler(userService, routerCreator)
	return userHandler
}
