// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"neema.co.za/rest/modules/user/api"
	"neema.co.za/rest/modules/user/repository"
	"neema.co.za/rest/modules/user/service"
	"neema.co.za/rest/utils/app"
	"neema.co.za/rest/utils/database"
)

// Injectors from wire_user.go:

func InjectUserModule() *api.Api {
	databaseDatabase := database.GetDatabase()
	repositoryRepository := repository.NewRepository(databaseDatabase)
	serviceService := service.NewService(repositoryRepository)
	routerCreator := app.NewRouter()
	apiApi := api.NewApi(serviceService, routerCreator)
	return apiApi
}
